### PR TITLE
Support raw html input for bootpopup.prompt

### PR DESCRIPTION
**Pull request by spidergears**
just like we do for custom dialogs

### CODE REVIEW

**Comment by rigon** [comment]
Sorry for the long time to respond. 

What is your use case to propose this feature? I cannot find it very useful... 🤔

**Comment by spidergears** [comment]
@rigon Thanks for looking into this. :)

For prompt, I needed `html select` support, for which either we can accept object representation or we can accept raw html.

I opted for the later implementation, to be able have support for any other html that might fit.

**Comment by rigon** [comment]
For this specific case, I prefer add support for selects.
Btw, I think this feature is useful, like adding a separator in between.

Stay tuned for the new release ;)

**Comment by rigon** [comment]
I just released version 1.5.1 with support for selects(including with multiple attribute), groups of radios inputs and raw HTML in prompt.

Check it out and update :D

**Pull request merged**
